### ISSUE TITLE
Error when students submit and finish work

### ISSUE THREAD

**Issue by mattgig** [projectestac/moodle-mod_geogebra#80] opened 2022-10-15 08:25 UTC
When students submit their work, the plugin throws the following error:

Exception - Argument 1 passed to grade_floatval() must be of the type float or null, string given, called in [dirroot]/lib/grade/grade_grade.php on line 1041

This error only occurs when the grade setting is NOT set to 'Average'.

Despite the error, the attempt is still saved an can be corrected by the teacher.

Workaround until the issue is fixed: Set grading with multiple attempts to average.

**Comment by toniginard** [comment] 2022-11-04 10:10
Hi @mattgig,

We were unable to reproduce the error. Can you share a ggb file causing the error?


Best wishes,

**Comment by PhMemmel** [comment] 2022-11-04 10:32
I can confirm the error:

![grafik](https://user-images.githubusercontent.com/65113153/199951892-98f29aca-f011-4c80-9497-010c56980ea0.png)

I set "grading method" to "highest attempt", opened the activity as student, clicked "Submit and finish" and received the error.

**Comment by toniginard** [comment] 2023-01-11 10:07
Hi @mattgig,

Last thursday I made a commit to master to fix this issue. Could you download the master branch and check if it now works for you?


Best wishes,
Toni Ginard

**Comment by toniginard** [comment] 2023-03-21 11:45
I assume that the change is correct, so I close the issue.

Best wishes,

**Closed by toniginard** 2023-03-21 11:45 UTC
