### ISSUE TITLE
Activities render blank in Moodle 3.9.7 (was working in Moodle 3.9.4)

### ISSUE THREAD

**Issue by harriholappa** [projectestac/moodle-mod_geogebra#56] opened 2021-06-09 10:36 UTC
After updating a Moodle site from 3.9.4 to 3.9.7, a user reported that all Geogebra activities now render as a blank white screen. There are no error messages showing up in Moodle debug mode. 

The developer console in Google Chrome says: "Uncaught TypeError: Cannot read property 'unzip' of undefined"

The developer console in Firefox is showing two error messages: "Uncaught TypeError: $wnd.window.fflate is undefined" and "Uncaught Error: Mismatched anonymous define() module: undefined http://requirejs.org/docs/errors.html#mismatch".

We also noticed a similar problem in a Moodle 3.9.6 installation. There a blank page also opens but with a loading icon in addition. 

Chrome console shows: "Uncaught TypeError: Cannot read property 'contentDocument' of null". 

Firefox console shows three messages: "downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:1) source: moz-extension://11aafc64-32c3-4e74-bdc2-14b50689167f/fonts/opensans/Semibold/OpenSans-Semibold.woff2?v=1.1.0"

"downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:1) source: moz-extension://11aafc64-32c3-4e74-bdc2-14b50689167f/fonts/opensans/Semibold/OpenSans-Semibold.woff2?v=1.1.0"

"Uncaught TypeError: editor is null"

Finally, we also have a Moodle 3.5.15 installation showing the same problems. The console error messages are pretty much the same as those in the 3.9.7 site.

Thank you for the plugin!

**Comment by toniginard** [comment] 2021-06-09 16:57
Hi!

The error _Uncaught TypeError: $wnd.window.fflate is undefined_ has nothing to do with the Moodle version. It is caused by a change in the javascript file the module loads from geogebra.org. Now it requires [fflate](https://www.npmjs.com/package/fflate). The lack of that requirement prevents the geogebra plugin to work in all cases.

We have added the loading of fflate in commit [15ef69](https://github.com/projectestac/moodle-mod_geogebra/commit/15ef693667734c920b4bba37ed40e35bf31e7752) and published [release 3.6.2](https://github.com/projectestac/moodle-mod_geogebra/releases/tag/v3.6.2) to include this change.

Could you try the new release before we close the issue?


Best wishes,

**Comment by harriholappa** [comment] 2021-06-10 05:19
Hello,

This fixed the issue. Thank you!

Best wishes,
Harri Holappa

**Comment by toniginard** [comment] 2021-06-10 12:01
Thanks for your feedback, Harri.

**Closed by toniginard** 2021-06-10 12:01 UTC
